### ISSUE TITLE
Get the questions automatically from an API

### ISSUE THREAD

**Issue by fatorius** [MakotoE/guess-the-eval#1]
Hello @MakotoE , I've just played Guess-the-eval and it's found it very fun to play.

I even looked around the code to see how it works and I noticed that all the questions are hard-coded in a .ts file right?
Do you have plans to update it somehow? Because right now even if I restart the program I'll get the same questions again.
Have you ever thought about creating a script that downloads some tournament games from an API [such as this one](https://github.com/prateeksan/chesspi) and chooses a random middle-game position, evaluates it using stockfish and generates a question?

The program could generate a couple of questions by the time the user is answering one.

If you think it could work and accept some help I could contribute to it.

I'm opening a fork and I'll try to implement this feature, but I would like to hear your thoughts on this first.

Anyways, congratulations for the project, it's really cool

**Comment by MakotoE** [comment]
Thanks. I'm in the middle of importing games from [The Week in Chess](https://theweekinchess.com/). What I'm trying to figure out is how to get good positions. Probably deleting the first couple turns from each game and boring endgames like kings + pawn should work. It's in progress inside [evaluator](https://github.com/MakotoE/guess-the-eval/tree/main/evaluator). Therefore I probably won't accept PRs for now but thanks for the offer.
