### ISSUE TITLE
Didnt find the best move even tho i played the best move

### ISSUE THREAD

**Issue by Wenceslaus-I** [MakotoE/guess-the-eval#10]
https://prnt.sc/kTvdBpBZ2iHg
as seen in this screenshot i played Rd8 and its stated under the board that Rd8 is the best move.
So i didnt get my multiplier even tho i should have. MAybe cause its a check and not listed in the top three moves as a check?

Greetings

**Comment by MakotoE** [comment]
This was fixed with https://github.com/MakotoE/guess-the-eval/commit/c2c1af25753d91f5af3f302f4023de73b3ec7065, though it has not been deployed yet.
