### ISSUE TITLE
Tells me that i didnt guess correct

### ISSUE THREAD

**Issue by noahfence332** [MakotoE/guess-the-eval#2]
I guessed 0.00 for eval and it said i was wrong and the correct eval was 0.00

**Comment by MakotoE** [comment]
I believe this is because the slider doesn't stop exactly at 0.0. It can stop at 0.00001 for example. A fix for this may be possible by rounding numbers close to 0.0 to 0.0.

**Comment by noahfence332** [comment]
Yea that could be interesting. I like the sliding scale but also could be nice to have a number somewhere that says the eval as you slide up and down.

**Comment by MakotoE** [comment]
If you're on mobile, you have to scroll right to see the current eval value. This is not an issue on desktop.

**Comment by noahfence332** [comment]
Oh gotcha. Would be cool to make this an app.
