### ISSUE TITLE
0.00 eval problem

### ISSUE THREAD

**Issue by aleksandar-mil** [MakotoE/guess-the-eval#21]
When correct answer is 0.00 and you guessed it, it says "You did not guess the winning side. Your eval guess was off by 0.00".
 I did not check the code but that looks like a problem to me.

**Comment by MakotoE** [comment]
Maybe this line needs to be improved https://github.com/MakotoE/guess-the-eval/blob/ac0864d5d9c2230cfe71ad07f261209b72b303cb/src/PointsSolver.ts#L38. Let's say the correct answer is -0.001 but you said 0.0, then the expression evaluates to false (0.0 * -0.001 > 0.0). But 0.0 * -0.001 >= 0.0 is true.

I'll deploy this once all the checks pass. https://github.com/MakotoE/guess-the-eval/pull/22
