### ISSUE TITLE
Positions with multiple best moves

### ISSUE THREAD

**Issue by JZ3007** [MakotoE/guess-the-eval#4]
I'm not sure what exactly is the issue, but in certain positions ([for example this one](https://lichess.org/analysis/standard/4r1k1/p3P2p/1p2r1p1/2n5/1P1Q2p1/B5P1/P1K4P/8%20b%20-%20-%200%2034)) where there are multiple best moves (2 in this case) you will not get points for finding the best move ([see screenshot](https://i.imgur.com/TO1ICqU.png)) .
I later got the same position and played the other best move and got points for finding the best move. Major difference here is that I got the evaluation right. Might do something with that?

**Comment by MakotoE** [comment]
Fixed with https://github.com/MakotoE/guess-the-eval/commit/c2c1af25753d91f5af3f302f4023de73b3ec7065. When you played Re2, the board outputted the string "Re2+" which was compared against the string "Re2" and it decided that these moves were not the same.
