### ISSUE TITLE
Guess the player seems broken

### ISSUE THREAD

**Issue by olarozenfeld** [MakotoE/guess-the-eval#7]
Bug: here you can see GM Hikaru Nakamura playing the game, and guessing the player correctly, yet not getting the points: https://youtu.be/hf9PCvs-bw0?t=1133
Suggestion: the player selection should be a dropdown menu instead of free text. That way, people don't have to guess the exact format required.

**Comment by MakotoE** [comment]
There is no player name input anymore because it was too challenging.

**Comment by olarozenfeld** [comment]
So how did it happen that Hikaru saw it? Your code updated but the UI didn't? Also, if you bring it back as a dropdown with, say, 5-7 options, it will maybe be more interesting...

**Comment by MakotoE** [comment]
The change was made after Hikaru's stream. I don't agree with the dropdown idea because again it is too challenging and because I don't think it adds element of fun. Thank you for the suggestion though.
